version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm install

  build:
    commands:
      - echo "Starting build with verbose output..."
      - set -x
      - npm run build

  post_build:
    commands:
      - echo "Build completed on $(date)"
      - |
        if [ -d scripts ]; then
          cp -r scripts/ build/
        else
          echo "Warning: scripts/ directory not found, skipping copy."
        fi

artifacts:
  files:
    - '**/*'
  base-directory: build
