version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install

  build:
    commands:
      - npm run build

  post_build:
    commands:
      - echo "Build completed on `date`"
      - echo "Artifacts copied from /build and /scripts"

artifacts:
  files:
    - '**/*'
    - ../scripts/**
  base-directory: build
